accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    # ex: /
    path('', views.TopView.as_view(), name='top'),
    # ex: /login/
    path('login/', views.TopLoginView.as_view(), name='login'),
    # ex: /logout/
    path('logout/', views.TopLogoutView.as_view(), name='logout'),

    # ex: /accounts/user_registration/
    path(app_name + '/user_registration/', views.UserRegistrationView.as_view(),
         name='user_registration'),
    # ex: /accounts/user_registration/send_mail/
    path(app_name + '/user_registration/complete/send_mail/', views.UserRegistrationMailView.as_view(),
         name='user_registration_send_mail'),
    # ex: /accounts/user_registration/<token>
    path(app_name + '/user_registration/complete/<token>', views.UserRegistrationCompleteView.as_view(),
         name='user_registration_complete'),
    # ex: /accounts/profile/2/
    path(app_name + '/profile/<int:pk>/', views.UserProfileView.as_view(),
         name='profile'),
    # ex: /accounts/profile/2/update/
    path(app_name + '/profile/<int:pk>/update/', views.UserProfileUpdateView.as_view(),
         name='profile_update'),
    # ex: /accounts/profile/2/password/
    path(app_name + '/profile/<int:pk>/password_change/', views.UserPasswordChangeView.as_view(),
         name='password_change'),
    # ex: /accounts/profile/2/password/complete
    path(app_name + '/profile/<int:pk>/password/complete/', views.UserPasswordChangeCompleteView.as_view(),
         name='password_change_complete'),
    # ex: /accounts/password_reset/
    path(app_name + '/password_reset/', views.UserPasswordResetView.as_view(),
         name='password_reset'),
    # ex: /accounts/password_reset/send_mail/
    path(app_name + '/password_reset/send_mail/', views.UserPasswordResetMailView.as_view(),
         name='password_reset_send_mail'),
    # ex: /accounts/password_reset/confirm/
    path(app_name + '/password_reset/confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    # ex: /accounts/password_reset/complete/
    path(app_name + '/password_reset/complete/', views.UserPasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('accounts.urls')),
    path('demand_manager/', include('demand_manager.urls')),
    path('admin/', admin.site.urls),
]

trialprj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('demand_manager/', include('demand_manager.urls')),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models

# Create your models here.


class CustomUserManager(BaseUserManager):
    """ Define a model manager for User model with no username field. """

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """ Create and save a User with the given email and password. """
        if not email:
            raise ValueError('The given email must be set.')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """ Create and save a regular User with the given email and password. """
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """ Create and save a SuperUser with the given email and password. """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    """ Custom User Model """

    username = models.CharField(
        'Username',
        max_length=150,
        blank=True,
        null=True,
        help_text="150 characters or fewer. Letters, digits and @/./+/-/_ only.",
        validators=[AbstractUser.username_validator],
    )
    email = models.EmailField('Email', unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    class Meta(AbstractUser.Meta):
        db_table = 'custom_user'

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordResetForm, SetPasswordForm
from django.contrib.auth import get_user_model

from .models import User
# User = get_user_model()


class LoginForm(AuthenticationForm):
    """Login Form"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class UserRegistrationForm(UserCreationForm):
    """User Registration Form"""

    class Meta:
        model = User
        fields = (
            'email',
            'password1', 'password2',
        )

    '''
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
    '''

    def clean_email(self):
        email = self.cleaned_data['email']
        User.objects.filter(email=email, is_active=False).delete()
        return email


class UserProfileUpdateForm(forms.ModelForm):
    """User Profile Update Form"""

    class Meta:
        model = User
        fields = (
            'username', 'email',
            'last_name', 'first_name',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

accounts/views.py
from django.views.generic import DetailView, TemplateView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth import get_user_model
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.sites.shortcuts import get_current_site
from django.core.signing import dumps, loads, SignatureExpired, BadSignature
from django.shortcuts import resolve_url, redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.http import Http404, HttpResponseBadRequest
from django.conf import settings

from .forms import LoginForm, UserProfileUpdateForm, UserRegistrationForm

from .models import User
#User = get_user_model()


# Create your views here.
class TopLoginView(LoginView):
    form_class = LoginForm
    template_name = "top/login.html"


class TopLogoutView(LogoutView):
    template_name = "top/logout.html"


class TopView(LoginRequiredMixin, TemplateView):
    template_name = "top/top.html"


class UserRegistrationView(CreateView):
    """User Registration"""
    model = User
    template_name = 'accounts/user_registration.html'
    form_class = UserRegistrationForm
    #success_url = reverse_lazy('accounts:user_registration_complete')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # Send Mail
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': self.request.scheme,
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }
        subject = render_to_string('accounts/email/user_registration_subject.txt', context)
        message = render_to_string('accounts/email/user_registration_message.txt', context)

        user.email_user(subject.strip(), message)
        return redirect('accounts:user_registration_send_mail')


class UserRegistrationMailView(TemplateView):
    """User Registration(Send Mail)"""
    template_name = 'accounts/user_registration_send_mail.html'


class UserRegistrationCompView(TemplateView):
    """Account Registration Complete"""
    template_name = 'accounts/user_registration_complete.html'


class UserRegistrationCompleteView(TemplateView):
    """Account Registration Complete"""
    template_name = 'accounts/user_registration_complete.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)  # 1day=60*60*24 sec

    def get(self, request, **kwargs):
        # Check token
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)

        # Timeout
        except SignatureExpired:
            return HttpResponseBadRequest()
        # Bad Token
        except BadSignature:
            return HttpResponseBadRequest()
        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoesNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    user.is_active = True
                    user.save()
                    return super().get(request, **kwargs)
        return HttpResponseBadRequest()


class UserOnlyMixin(UserPassesTestMixin):
    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser


class UserProfileView(UserOnlyMixin, DetailView):
    """User Profile"""
    model = User
    template_name = 'accounts/user_profile.html'


class UserProfileUpdateView(UserOnlyMixin, UpdateView):
    """User Profile Update"""
    model = User
    form_class = UserProfileUpdateForm
    template_name = 'accounts/user_profile_update.html'

    def get_success_url(self):
        return resolve_url('accounts:profile', pk=self.kwargs['pk'])


class UserPasswordChangeView(UserOnlyMixin, PasswordChangeView):
    """User Password Change"""
    model = User
    template_name = 'accounts/user_password_change.html'

    def get_success_url(self):
        return resolve_url('accounts:password_change_complete', pk=self.kwargs['pk'])


class UserPasswordChangeCompleteView(UserOnlyMixin, PasswordChangeDoneView):
    """User Password Change Complete"""
    template_name = 'accounts/user_password_change_complete.html'


class UserPasswordResetView(PasswordResetView):
    """User Password Reset Request"""
    subject_template_name = 'accounts/email/user_password_reset_subject.txt'
    email_template_name = 'accounts/email/user_password_reset_message.txt'
    template_name = 'accounts/user_password_reset.html'
    success_url = reverse_lazy('accounts:password_reset_send_mail')


class UserPasswordResetMailView(PasswordResetDoneView):
    """User Password Reset(Send Reset Mail)"""
    template_name = 'accounts/user_password_reset_send_mail.html'


class UserPasswordResetConfirmView(PasswordResetConfirmView):
    """User Password Reset"""
    template_name = 'accounts/user_password_reset_confirm.html'
    success_url = reverse_lazy('accounts:password_reset_complete')


class UserPasswordResetCompleteView(PasswordResetCompleteView):
    """User Password Reset Complete"""
    template_name = 'accounts/user_password_reset_complete.html'

accounts/templates/accounts/base.html
../top/base.html

accounts/templates/accounts/top_block_navbar_contents.html
../top/top_block_navbar_contents.html

accounts/templates/accounts/user_password_change.html
{% extends "./base.html" %}
{% load crispy_forms_tags %}
{% block page_title %} Demand Manager Change Password {% endblock %}

{% block navbar_title %}Account Management{% endblock%}

{% block navbar_contents %}
{% include "./top_block_navbar_contents.html" %}
{% endblock %}

{% block content %}
<div style="margin:20px">
    <form action="" method="POST">
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" class="btn btn-success">Change</button>
        <a href="{% url 'accounts:profile' user.pk %}" class="btn btn-primary">Back</a>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/user_password_change_complete.html
{% extends "./base.html" %}
{% block page_title %} Demand Manager Change Password(Success) {% endblock %}

{% block navbar_title %}Account Management{% endblock%}

{% block navbar_contents %}
{% include "./top_block_navbar_contents.html" %}
{% endblock %}

{% block content %}
<div style="text-align: center; padding-top: 50px;">
    <h2>Change user password successfully</h2>
    <a href="{% url 'accounts:profile' user.pk %}" class="btn btn-primary">User Info</a>
</div>
{% endblock%}

accounts/templates/accounts/user_password_reset.html
{% extends "./base.html" %}
{% block page_title %} Demand Manager Reset Password Request {% endblock %}

{% block navbar_title %}Account Management{% endblock%}

{% block navbar_contents %}
{% include "./top_block_navbar_contents.html" %}
{% endblock %}

{% block content %}
<h2>Password Reset Request</h2>
<div style="margin:20px">
    <form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-success">Send</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/user_password_reset_complete.html
{% extends "./base.html" %}
{% block page_title %} Demand Manager Reset Complete {% endblock %}

{% block navbar_title %}Account Management{% endblock%}

{% block navbar_contents %}
{% include "./top_block_navbar_contents.html" %}
{% endblock %}

{% block content %}
<div style="margin:20px">
    <h2 >Password Reset Complete!</h2>
    <a href="{% url 'accounts:login' %}">Login</a>
</div>
{% endblock %}

accounts/templates/accounts/user_password_reset_confirm.html
{% extends "./base.html" %}
{% block page_title %} Demand Manager Reset Password Form {% endblock %}

{% block navbar_title %}Account Management{% endblock%}

{% block navbar_contents %}
{% include "./top_block_navbar_contents.html" %}
{% endblock %}

{% block content %}
<h2>Password Reset</h2>
<div style="margin:20px">
    <form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-success">Send</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/user_password_reset_send_mail.html
{% extends "./base.html" %}
{% block page_title %} Demand Manager Reset(Send Mail) {% endblock %}

{% block navbar_title %}Account Management{% endblock%}

{% block navbar_contents %}
{% include "./top_block_navbar_contents.html" %}
{% endblock %}

{% block content %}
<h2>Password Reset Request(Send Mail)</h2>
<div style="margin:20px">
    <p>
        Mail for resetting your password has been sent. <br>
        Please reset your password from the link described in the mail.
    </p>
</div>
{% endblock %}

accounts/templates/accounts/user_profile.html
{% extends "./base.html" %}
{% block page_title %} Demand Manager User Profile {% endblock %}

{% block navbar_title %}Account Management{% endblock%}

{% block navbar_contents %}
{% include "./top_block_navbar_contents.html" %}
{% endblock %}

{% block content %}
<div style="margin:20px">
    <table class="table">
        <tbody>
            <tr>
                <th>User Name</th>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <th>Mail Address</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Last Name</th>
                <td>{{ user.last_name }}</td>
            </tr>
            <tr>
                <th>First Name</th>
                <td>{{ user.first_name }}</td>
            </tr>
        </tbody>
    </table>
    <a href="{% url 'accounts:profile_update' user.pk %}" class="btn btn-primary ">Update</a>
    <a href="{% url 'accounts:password_change' user.pk %}" class="btn btn-primary">Change Password</a>
</div>
{% endblock %}

accounts/templates/accounts/user_profile_update.html
{% extends "./base.html" %}
{% load crispy_forms_tags %}
{% block page_title %} Demand Manager User Profile Update{% endblock %}

{% block navbar_title %}Account Management{% endblock%}

{% block navbar_contents %}
{% include "./top_block_navbar_contents.html" %}
{% endblock %}

{% block content %}
<div style="margin:20px">
    <form action="" method="POST" enctype="multipart/form-data">
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" class="btn btn-success">Update</button>
        <a href="{% url 'accounts:profile' user.pk %}" class="btn btn-primary">Back</a>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/user_registration.html
{% extends "./base.html" %}
{% load crispy_forms_tags %}
{% block page_title %} Demand Manager User Registration {% endblock%}

{% block navbar_title %}Account Management{% endblock%}

{% block navbar_contents %}
{% include "./top_block_navbar_contents.html" %}
{% endblock %}

{% block content %}
<div style="padding:20px 200px 0px 200px;">
    <form action="" method="POST">
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-lg">Register</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/user_registration_complete.html
{% extends "./base.html" %}
{% block page_title %} Demand Manager User Registration Complete {% endblock%}

{% block navbar_title %}Account Management{% endblock%}

{% block navbar_contents %}
{% include "./top_block_navbar_contents.html" %}
{% endblock %}

{% block content %}
<div style="text-align: center; padding-top: 50px;">
    <h2 >User Registration Complete!</h2>
    <a href="{% url 'accounts:login' %}">Login</a>
</div>
{% endblock %}

accounts/templates/accounts/user_registration_send_mail.html
{% extends "./base.html" %}
{% block page_title %} Demand Manager User Registration(Send Mail) {% endblock %}

{% block navbar_title %}Account Management{% endblock%}

{% block navbar_contents %}
{% include "./top_block_navbar_contents.html" %}
{% endblock %}

{% block content %}
<h2>User Registration Request(Send Mail)</h2>
<div style="margin:20px">
    <p>
        Mail for user registration has been sent. <br>
        Please access the link described in the mail.
    </p>
</div>
{% endblock %}