accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    # ex: /
    path('', views.TopView.as_view(), name='top'),
    # ex: /login/
    path('login/', views.TopLoginView.as_view(), name='login'),
    # ex: /logout/
    path('logout/', views.TopLogoutView.as_view(), name='logout'),

    # ex: /accounts/user_registration/
    path(app_name + '/user_registration/', views.UserRegistrationView.as_view(),
         name='user_registration'),
    # ex: /accounts/user_registration/send_mail/
    path(app_name + '/user_registration/complete/send_mail/', views.UserRegistrationMailView.as_view(),
         name='user_registration_send_mail'),
    # ex: /accounts/user_registration/<token>
    path(app_name + '/user_registration/complete/<token>', views.UserRegistrationCompleteView.as_view(),
         name='user_registration_complete'),
    # ex: /accounts/profile/2/
    path(app_name + '/profile/<int:pk>/', views.UserProfileView.as_view(),
         name='profile'),
    # ex: /accounts/profile/2/update/
    path(app_name + '/profile/<int:pk>/update/', views.UserProfileUpdateView.as_view(),
         name='profile_update'),
    # ex: /accounts/profile/2/password/
    path(app_name + '/profile/<int:pk>/password_change/', views.UserPasswordChangeView.as_view(),
         name='password_change'),
    # ex: /accounts/profile/2/password/complete
    path(app_name + '/profile/<int:pk>/password/complete/', views.UserPasswordChangeCompleteView.as_view(),
         name='password_change_complete'),
    # ex: /accounts/password_reset/
    path(app_name + '/password_reset/', views.UserPasswordResetView.as_view(),
         name='password_reset'),
    # ex: /accounts/password_reset/send_mail/
    path(app_name + '/password_reset/send_mail/', views.UserPasswordResetMailView.as_view(),
         name='password_reset_send_mail'),
    # ex: /accounts/password_reset/confirm/
    path(app_name + '/password_reset/confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    # ex: /accounts/password_reset/complete/
    path(app_name + '/password_reset/complete/', views.UserPasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('accounts.urls')),
    path('demand_manager/', include('demand_manager.urls')),
    path('admin/', admin.site.urls),
]

demand_manager/urls.py
from django.urls import path
from . import views

app_name = 'demand_manager'
urlpatterns = [
    # ex: /demand_manager/
    # path('', views.DemandTopView.as_view(), name='top'),
    path('', views.DemandTopFilterView.as_view(), name='top'),

    # ex: /demand_manager/login/
    #path('login/', views.DemandLoginView.as_view(), name='login'),
    # ex: /demand_manager/logout/
    #path('logout/', views.DemandLogoutView.as_view(), name='logout'),

    # ex: /demand_manager/create/
    path('create/', views.DemandCreateView.as_view(), name='create'),
    # ex: /demand_manager//2/
    path('<int:pk>/', views.DemandDetailView.as_view(), name='detail'),
    # ex: /demand_manager/2/update/
    path('<int:pk>/update/', views.DemandUpdateView.as_view(), name='update'),
    # ex: /demand_manager/2/delete/
    path('<int:pk>/delete/', views.DemandDeleteView.as_view(), name='delete'),
    # ex: /demand_manager/analysis/
    path('analysis/', views.DemandAnalysisView.as_view(), name='analysis'),
    # ex: /demand_manager/import/
    path('import/', views.ImportReleasedLicenseView.as_view(), name='import'),
]

trialprj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('demand_manager/', include('demand_manager.urls')),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models

# Create your models here.


class CustomUserManager(BaseUserManager):
    """ Define a model manager for User model with no username field. """

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """ Create and save a User with the given email and password. """
        if not email:
            raise ValueError('The given email must be set.')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """ Create and save a regular User with the given email and password. """
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """ Create and save a SuperUser with the given email and password. """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    """ Custom User Model """

    username = models.CharField(
        'Username',
        max_length=150,
        blank=True,
        null=True,
        help_text="150 characters or fewer. Letters, digits and @/./+/-/_ only.",
        validators=[AbstractUser.username_validator],
    )
    email = models.EmailField('Email', unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    class Meta(AbstractUser.Meta):
        db_table = 'custom_user'

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordResetForm, SetPasswordForm
from django.contrib.auth import get_user_model

from .models import User
# User = get_user_model()


class LoginForm(AuthenticationForm):
    """Login Form"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class UserRegistrationForm(UserCreationForm):
    """User Registration Form"""

    class Meta:
        model = User
        fields = (
            'email',
            'password1', 'password2',
        )

    '''
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
    '''

    def clean_email(self):
        email = self.cleaned_data['email']
        User.objects.filter(email=email, is_active=False).delete()
        return email


class UserProfileUpdateForm(forms.ModelForm):
    """User Profile Update Form"""

    class Meta:
        model = User
        fields = (
            'username', 'email',
            'last_name', 'first_name',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

accounts/views.py
from django.views.generic import DetailView, TemplateView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth import get_user_model
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.sites.shortcuts import get_current_site
from django.core.signing import dumps, loads, SignatureExpired, BadSignature
from django.shortcuts import resolve_url, redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.http import Http404, HttpResponseBadRequest
from django.conf import settings

from .forms import LoginForm, UserProfileUpdateForm, UserRegistrationForm

from .models import User
#User = get_user_model()


# Create your views here.
class TopLoginView(LoginView):
    form_class = LoginForm
    template_name = "top/login.html"


class TopLogoutView(LogoutView):
    template_name = "top/logout.html"


class TopView(LoginRequiredMixin, TemplateView):
    template_name = "top/top.html"


class UserRegistrationView(CreateView):
    """User Registration"""
    model = User
    template_name = 'accounts/user_registration.html'
    form_class = UserRegistrationForm
    #success_url = reverse_lazy('accounts:user_registration_complete')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # Send Mail
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': self.request.scheme,
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }
        subject = render_to_string('accounts/email/user_registration_subject.txt', context)
        message = render_to_string('accounts/email/user_registration_message.txt', context)

        user.email_user(subject.strip(), message)
        return redirect('accounts:user_registration_send_mail')


class UserRegistrationMailView(TemplateView):
    """User Registration(Send Mail)"""
    template_name = 'accounts/user_registration_send_mail.html'


class UserRegistrationCompView(TemplateView):
    """Account Registration Complete"""
    template_name = 'accounts/user_registration_complete.html'


class UserRegistrationCompleteView(TemplateView):
    """Account Registration Complete"""
    template_name = 'accounts/user_registration_complete.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)  # 1day=60*60*24 sec

    def get(self, request, **kwargs):
        # Check token
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)

        # Timeout
        except SignatureExpired:
            return HttpResponseBadRequest()
        # Bad Token
        except BadSignature:
            return HttpResponseBadRequest()
        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoesNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    user.is_active = True
                    user.save()
                    return super().get(request, **kwargs)
        return HttpResponseBadRequest()


class UserOnlyMixin(UserPassesTestMixin):
    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser


class UserProfileView(UserOnlyMixin, DetailView):
    """User Profile"""
    model = User
    template_name = 'accounts/user_profile.html'


class UserProfileUpdateView(UserOnlyMixin, UpdateView):
    """User Profile Update"""
    model = User
    form_class = UserProfileUpdateForm
    template_name = 'accounts/user_profile_update.html'

    def get_success_url(self):
        return resolve_url('accounts:profile', pk=self.kwargs['pk'])


class UserPasswordChangeView(UserOnlyMixin, PasswordChangeView):
    """User Password Change"""
    model = User
    template_name = 'accounts/user_password_change.html'

    def get_success_url(self):
        return resolve_url('accounts:password_change_complete', pk=self.kwargs['pk'])


class UserPasswordChangeCompleteView(UserOnlyMixin, PasswordChangeDoneView):
    """User Password Change Complete"""
    template_name = 'accounts/user_password_change_complete.html'


class UserPasswordResetView(PasswordResetView):
    """User Password Reset Request"""
    subject_template_name = 'accounts/email/user_password_reset_subject.txt'
    email_template_name = 'accounts/email/user_password_reset_message.txt'
    template_name = 'accounts/user_password_reset.html'
    success_url = reverse_lazy('accounts:password_reset_send_mail')


class UserPasswordResetMailView(PasswordResetDoneView):
    """User Password Reset(Send Reset Mail)"""
    template_name = 'accounts/user_password_reset_send_mail.html'


class UserPasswordResetConfirmView(PasswordResetConfirmView):
    """User Password Reset"""
    template_name = 'accounts/user_password_reset_confirm.html'
    success_url = reverse_lazy('accounts:password_reset_complete')


class UserPasswordResetCompleteView(PasswordResetCompleteView):
    """User Password Reset Complete"""
    template_name = 'accounts/user_password_reset_complete.html'

accounts/templates/top/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    {% block extra_css %}{% endblock%}

    <title>{% block page_title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        {% block navbar_title %}{% endblock %}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'accounts:top' %}">
                        <i class="fas fa-home"></i> Home <span class="sr-only">(current)</span></a>
                </li>

                {% block navbar_contents %}{% endblock %}

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownDoc" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-book"></i> Documents
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownDoc">
                        <a class="dropdown-item" href="#">Users Manual(In preparation)</a>
                        <a class="dropdown-item" href="#">Update Plan(In preparation)</a>
                        {% if user.is_staff %}
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Administrator Manual(In preparation)</a>
                        {% endif %}
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item disabled" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownLink" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-link"></i> Link
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownLink">
                        <a class="dropdown-item" href="#">Link #1</a>
                        <a class="dropdown-item" href="#">Link #2</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item disabled" href="#">Something else here</a>
                    </div>
                </li>
                <!--
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
                -->
            </ul>
            <div class="btn-group">
                <div class="btn dropdown-toggle naviDrop" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {% if user.is_authenticated %}
                       <i class="fas fa-user-circle"></i> User : {{ user.get_username }}
                    {% else %}
                        User
                    {% endif %}
                </div>
                {% if user.is_authenticated %}
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" href="{% url 'accounts:profile' user.pk %}">
                            <i class="fas fa-user-cog"></i> User Info
                        </a>
                        {% if user.is_staff %}
                            <div class="dropdown-divider"></div>
                            <h6 class="dropdown-header"> Administrator Menu </h6>
                            <a class="dropdown-item" href="{% url 'demand_manager:analysis' %}">
                                <i class="fas fa-chart-bar"></i> Demand Analysis</a>
                            <a class="dropdown-item" href="{% url 'demand_manager:import' %}">
                                <i class="fas fa-file-upload"></i> Import License File</a>
                            <a class="dropdown-item" href="/admin/">
                                <i class="fas fa-users-cog"></i> Setup </a>
                        {% endif %}
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'accounts:logout' %}">
                            <i class="fas fa-sign-out-alt"></i> Logout
                        </a>
                    </div>
                {% endif %}
            </div>
            <!--
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
            -->
        </div>
    </nav>

    <div class="ui container">
        {% block content %}{% endblock %}
    </div>

    <div class="footer">
        <div class="container">
            <hr>
            <div class="copyright">
                <p>
                    &copy; Copyright 2019, <a href="mailto:#">Hirotaka Yamazaki</a>
                </p>
                <p>
                    Built with <a href="https://www.djangoproject.com/">Django</a>
                </p>
            </div>
        </div>
    </div>

    <!-- Optional JavaScript -->

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous">
    </script>
    {% block extra_js %}{% endblock %}
</body>

</html>

accounts/templates/top/login.html
{% extends "./base.html" %}
{% load crispy_forms_tags %}
{% block page_title %} Login {% endblock%}

{% block navbar_title %}
    <a class="navbar-brand" href="#">Account Management</a>
{% endblock %}

{% block navbar_contents %}
{% include "./top_block_navbar_contents.html" %}
{% endblock %}

{% block content %}
<div style="padding-top: 50px;">
    <form action="" method="POST">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body">
                    {{ form|crispy }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-lg btn-primary btn-block" >Login</button>
                    <input type="hidden" name="next" value="{{ next }}" />
                    <a class="btn btn-lg btn-warning btn-block mt-2"
                       href="{% url 'accounts:password_reset' %}"> Password Reset</a>
                    <a class="btn btn-lg btn-outline-primary btn-block mt-2"
                       href="{% url 'accounts:user_registration' %}"> User Registration</a>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

accounts/templates/top/logout.html
{% extends "./base.html" %}
{% block page_title %} Demand Manager Logout {% endblock %}

{% block navbar_title %}
<a class="navbar-brand" href="#">Account Management</a>
{% endblock %}

{% block navbar_contents %}
{% include "./top_block_navbar_contents.html" %}
{% endblock %}

{% block content %}
    <div style="text-align: center; padding-top: 50px;">
    <h2 >See you!</h2>
    <a href="{% url 'accounts:login' %}">Login</a>
    </div>
{% endblock %}

accounts/templates/top/top.html
{% extends "./base.html"%}

{% block page_title %}Top{% endblock %}

{% block navbar_title %}
    <a class="navbar-brand" href="#">Top</a>
{% endblock %}

{% block navbar_contents %}
{% include "./top_block_navbar_contents.html" %}
{% endblock %}

{% block content %}
    <div>
        <h1>Topics</h1>
        <ul>
            <li>2019/06/xx: Start operation of <a href="/demand_manager">Demand Manager</a></li>
        </ul>
    </div>

    <hr>
    <div>
        <h1>Contents</h1>
        <h2><a href="/demand_manager">Demand Manager</a></h2>
        <h2><a href="#">Web Application2</a></h2>
        <h2><a href="#">Web Application3</a></h2>
    </div>
{% endblock %}

accounts/templates/top/top_block_navbar_contents.html
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'demand_manager:top' %}">
                        <i class="far fa-calendar-plus"></i>Demand Manager</a>
                </li>