config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('accounts.urls')),
    path('demand_manager/', include('demand_manager.urls')),
    path('admin/', admin.site.urls),
]

demand_manager/urls.py
from django.urls import path
from . import views

app_name = 'demand_manager'
urlpatterns = [
    # ex: /demand_manager/
    # path('', views.DemandTopView.as_view(), name='top'),
    path('', views.DemandTopFilterView.as_view(), name='top'),

    # ex: /demand_manager/login/
    #path('login/', views.DemandLoginView.as_view(), name='login'),
    # ex: /demand_manager/logout/
    #path('logout/', views.DemandLogoutView.as_view(), name='logout'),

    # ex: /demand_manager/create/
    path('create/', views.DemandCreateView.as_view(), name='create'),
    # ex: /demand_manager//2/
    path('<int:pk>/', views.DemandDetailView.as_view(), name='detail'),
    # ex: /demand_manager/2/update/
    path('<int:pk>/update/', views.DemandUpdateView.as_view(), name='update'),
    # ex: /demand_manager/2/delete/
    path('<int:pk>/delete/', views.DemandDeleteView.as_view(), name='delete'),
    # ex: /demand_manager/analysis/
    path('analysis/', views.DemandAnalysisView.as_view(), name='analysis'),
    # ex: /demand_manager/import/
    path('import/', views.ImportReleasedLicenseView.as_view(), name='import'),
]

trialprj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('demand_manager/', include('demand_manager.urls')),
    path('admin/', admin.site.urls),
]

demand_manager/forms.py
from django import forms
from datetime import date, timedelta
from dateutil.relativedelta import relativedelta
from django.core.files.storage import default_storage
from django.core.mail import EmailMessage

from .models import Demand, Release


class DemandCreateForm(forms.ModelForm):
    """Demand Create"""

    class Meta:
        model = Demand
        fields = (
            'product', 'product_id',
            'tech_node',
            'content',
            'start_date', 'end_date',
            'frequency', 'comment'
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
        self.fields['start_date'].widget.input_type = 'date'
        self.fields['end_date'].widget.input_type = 'date'

    '''
    def clean_start_date(self):
        start_date = self.cleaned_data['start_date']
        if start_date < date.today():
            raise forms.ValidationError("The date cannot be set in the past!")
        return start_date
    '''

    def clean(self):
        start_date = self.cleaned_data['start_date']
        end_date = self.cleaned_data['end_date']
        today = date.today()
        if start_date < today:
            raise forms.ValidationError("The start date cannot be set in the past!({0} < Today: {1})"
                                        .format(start_date, today))
        elif start_date > end_date:
            raise forms.ValidationError("The end date is later than the start date(End: {0} < Start: {1})"
                                        .format(end_date, start_date))

    def send_email(self):
        product = self.cleaned_data['product']
        product_id = self.cleaned_data['product_id']
        tech_node = self.cleaned_data['tech_node']
        content = self.cleaned_data['content']
        start_date = self.cleaned_data['start_date']
        end_date = self.cleaned_data['end_date']
        frequency = self.cleaned_data['frequency']
        comment = self.cleaned_data['comment']

        subject = 'Demand Creation {0} for {1}'.format(content, product)
        message = 'From: Administrator of Demand Manager\n' + \
                  '<Registered Items>\n' + \
                  ' ' * 2 + 'Product: {}\n'.format(product) + \
                  ' ' * 2 + 'Product ID: {}\n'.format(product_id) + \
                  ' ' * 2 + 'Technology Node: {}\n'.format(tech_node) + \
                  ' ' * 2 + 'Verification Content: {}\n'.format(content) + \
                  ' ' * 2 + 'Date of Start: {}\n'.format(start_date) + \
                  ' ' * 2 + 'Date of End: {}\n'.format(end_date) + \
                  ' ' * 2 + 'Frequency[%]: {}\n'.format(frequency) + \
                  ' ' * 2 + 'Comment: {}\n'.format(comment)
        from_email = 'admin@example.com'
        to_list = ['test@example.com']
        bcc_list = ['admin@example.com']

        email = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, bcc=bcc_list)
        email.send()


class DemandUpdateForm(forms.ModelForm):
    """Demand Update"""

    class Meta:
        model = Demand
        fields = (
            'product', 'product_id',
            'tech_node',
            'content',
            'start_date', 'end_date',
            'frequency', 'comment'
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['start_date'].widget.input_type = 'date'
        self.fields['end_date'].widget.input_type = 'date'

    def clean(self):
        start_date = self.cleaned_data['start_date']
        end_date = self.cleaned_data['end_date']
        if start_date > end_date:
            raise forms.ValidationError("The end date is later than the start date")


class DemandAnalysisForm(forms.Form):
    period_start = forms.DateField(
        label="Date of Start",
        initial=date.today(),
        widget=forms.DateInput(attrs={"type":"date"}),
    )
    period_end = forms.DateField(
        label="Date of End",
        initial=date.today() + relativedelta(months=1) - timedelta(days=1),
        widget=forms.DateInput(attrs={"type":"date"}),
    )
    reference_hours = forms.IntegerField(
        label = "Reference hours per day",
        initial = 8,
    )


class ImportReleasedLicenseForm(forms.Form):
    license_type = forms.ChoiceField(
        label="License Type",
        choices=Release.lic_type_choice,
    )
    license_file = forms.FileField(
        label="License File",
        help_text="Set License File.",
    )

    def upload(self):
        upload_file = self.cleaned_data['license_file']
        license_type = self.cleaned_data['license_type']
        file_name = default_storage.save("demand_manager/license/" + upload_file.name, upload_file)
        return license_type, default_storage.url(file_name)

demand_manager/views.py
import io
import os
import logging
from django.views.generic import DetailView, FormView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django_filters.views import FilterView
from django.shortcuts import resolve_url
from django.utils import timezone
from django.urls import reverse_lazy

from datetime import datetime, date

from .models import Demand
from .forms import DemandCreateForm, DemandUpdateForm, DemandAnalysisForm, ImportReleasedLicenseForm
from .filters import DemandFilter
from demand_manager.utils.demand_summary import DemandFeature
from demand_manager.utils.import_lic import ReleaseLic

logger = logging.getLogger(__name__)


# Create your views here.
class DemandTopFilterView(LoginRequiredMixin, FilterView):
    model = Demand
    filterset_class = DemandFilter
    template_name = "demand_manager/demand_top_filter.html"

    paginate_by = 10

    '''
    def get(self, request, **kwargs):
        if request.GET:
            request.session['query'] = request.GET
        else:
            request.GET = request.GET.copy()
            if 'query' in request.session.keys():
                for key in request.session['query'].keys():
                    request.GET[key] = request.session['query'][key]
        return super().get(request, **kwargs)
    '''

    def get_queryset(self):
        return Demand.objects.all().order_by('start_date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list_from_today'] = Demand.objects.filter(end_date__gt=date.today()).order_by('start_date')
        return context


class DemandDetailView(LoginRequiredMixin, DetailView):
    model = Demand
    template_name = 'demand_manager/demand_detail.html'


class DemandCreateView(LoginRequiredMixin, CreateView):
    model = Demand
    template_name = 'demand_manager/demand_create.html'
    form_class = DemandCreateForm
    success_url = '/demand_manager'

    def form_valid(self, form):
        """

        :param form:
        :return:
        """
        demand = form.save(commit=False)
        demand.user_create = self.request.user
        demand.time_create = timezone.now()
        demand.user_update = self.request.user
        demand.time_update = timezone.now()
        demand.save()

        # Send Mail
        form.send_email()

        logger.info('Demand({0}) registered by {1}'
                    .format(form.cleaned_data['product'], demand.user_create))

        return super().form_valid(form)


class DemandUpdateView(LoginRequiredMixin, UpdateView):
    model = Demand
    template_name = 'demand_manager/demand_update.html'
    form_class = DemandUpdateForm

    def get_success_url(self):
        return resolve_url('demand_manager:detail', pk=self.kwargs['pk'])

    def form_valid(self, form):
        """

        :param form:
        :return:
        """
        demand = form.save(commit=False)
        demand.user_update = self.request.user
        demand.time_update = timezone.now()
        demand.save()

        logger.info('Demand({0}) updated by user id({1})'
                    .format(form.cleaned_data['product'], demand.user_update))

        return super().form_valid(form)


class DemandDeleteView(LoginRequiredMixin, DeleteView):
    model = Demand
    template_name = 'demand_manager/demand_delete_confirm.html'
    success_url = '/demand_manager'


class DemandAnalysisView(LoginRequiredMixin, FormView):
    form_class = DemandAnalysisForm
    template_name = 'demand_manager/demand_analysis.html'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        period_start = self.request.GET.get(key='period_start')
        period_end = self.request.GET.get(key='period_end')
        reference_hours = self.request.GET.get(key='reference_hours')
        # Calc Demand Feature
        demand_feature = DemandFeature(period_start, period_end, reference_hours)
        demand_feature.demand_summary()
        context['df_demand_feature'] = demand_feature.df_demand_feature
        context['df_summary'] = demand_feature.df_summary
        context['df_png_path'] = demand_feature.df_png_path
        if type(demand_feature.start_date) is str:
            context['period_start'] = datetime.strptime(demand_feature.start_date, '%Y-%m-%d')
        else:
            context['period_start'] = demand_feature.start_date
        if type(demand_feature.end_date) is str:
            context['period_end'] = datetime.strptime(demand_feature.end_date, '%Y-%m-%d')
        else:
            context['period_end'] = demand_feature.end_date
        context['reference_hours'] = demand_feature.ref_hours
        return context


class ImportReleasedLicenseView(LoginRequiredMixin, FormView):
    form_class = ImportReleasedLicenseForm
    template_name = 'demand_manager/import_released_license.html'
    success_url = reverse_lazy('demand_manager:top')

    def form_valid(self, form):
        lic_type, download_url = form.upload()
        ReleaseLic(lic_type, os.getcwd() + download_url).add_feature2db()
        return super().form_valid(form)

demand_manager/templates/demand_manager/base.html
../../../accounts/templates/top/base.html

demand_manager/templates/demand_manager/demand_block_navbar_contents.html
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'demand_manager:create' %}">
                        <i class="far fa-calendar-plus"></i> Add Demand</a>
                </li>
                {% if user.is_staff %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'demand_manager:analysis' %}">
                        <i class="fas fa-chart-bar"></i> Demand Analysis</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'demand_manager:import' %}">
                        <i class="fas fa-file-upload"></i> Import License File</a>
                </li>
                {% endif %}

demand_manager/templates/demand_manager/demand_create.html
{% extends "./base.html" %}
{% load crispy_forms_tags %}

{% block page_title %} Demand Manager Demand Creation {% endblock%}

{% block navbar_title %}
    <a class="navbar-brand" href="{% url 'demand_manager:top' %}">Demand Manager</a>
{% endblock%}

{% block navbar_contents %}
{% include "./demand_block_navbar_contents.html" %}
{% endblock %}

{% block content %}
<div style="padding:20px 200px 0px 200px;">
    <form action="" method="POST">
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-lg">Add</button>
        <a href="{% url 'demand_manager:top' %}" class="btn btn-primary btn-lg">Back</a>
    </form>
</div>
{% endblock %}

demand_manager/templates/demand_manager/demand_delete_confirm.html
{% extends "./base.html" %}
{% load crispy_forms_tags %}
{% block page_title %} Demand Manager Demand Delete {% endblock%}

{% block navbar_title %}
    <a class="navbar-brand" href="{% url 'demand_manager:top' %}">Demand Manager</a>
{% endblock%}

{% block navbar_contents %}
{% include "./demand_block_navbar_contents.html" %}
{% endblock %}


{% block content %}
<div class="container">
    <h2>Deletion confirmation</h2>
    <hr>
    <p>Do you want to delete this demand?</p>
    <table class="table table-bordered table-striped table-light">
        <thead>
            <tr class="table-primary">
                <th scope="col">Product</th>
                <th scope="col">Product ID</th>
                <th scope="col">Technology Node</th>
                <th scope="col">Verification</th>
                <th scope="col">Date of Start</th>
                <th scope="col">Date of End</th>
                <th scope="col">Frequency [%]</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">{{ demand.product }}</th>
                <td>{{ demand.product_id }}</td>
                <td>{{ demand.tech_node }}</td>
                <td>{{ demand.content }}</td>
                <td>{{ demand.start_date|date:"Y/m/d" }}</td>
                <td>{{ demand.end_date|date:"Y/m/d"}}</td>
                <td>{{ demand.frequency }}</td>
            </tr>
        </tbody>
    </table>
    <form action="" method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-secondary">Delete</button>
        <a href="{% url 'demand_manager:top' %}" class="btn btn-primary">Back</a>
    </form>
</div>
{% endblock %}

demand_manager/templates/demand_manager/demand_detail.html
{% extends "./base.html" %}
{% block page_title %}Demand Manager Demand Detail{% endblock %}

{% block navbar_title %}
    <a class="navbar-brand" href="{% url 'demand_manager:top' %}">Demand Manager</a>
{% endblock%}

{% block navbar_contents %}
{% include "./demand_block_navbar_contents.html" %}
{% endblock %}

{% block content %}
<div style="margin:20px">
    <table class="table table-bordered table-striped table-light">
        <tbody>
            <tr>
                <th scope="row">Product Name</th>
                <td>{{  demand.product|default_if_none:"N/A"  }}</td>
            </tr>
            <tr>
                <th scope="row">Product ID</th>
                <td>{{  demand.product_id|default_if_none:"N/A"  }}</td>
            </tr>
            <tr>
                <th scope="row">Technology Node</th>
                <td>{{  demand.tech_node|default_if_none:"N/A"  }}</td>
            </tr>
            <tr>
                <th scope="row">Verification Content</th>
                <td>{{  demand.content|default_if_none:"N/A"  }}</td>
            </tr>
            <tr>
                <th scope="row">Start Date</th>
                <td>{{  demand.start_date|date:"Y/m/d"  }}</td>
            </tr>
            <tr>
                <th scope="row">End Date</th>
                <td>{{  demand.end_date|date:"Y/m/d"  }}</td>
            </tr>
            <tr>
                <th scope="row">Frequency of use [%]</th>
                <td>{{  demand.frequency|default_if_none:"N/A" }}</td>
            </tr>
            <tr>
                <th scope="row">Comments</th>
                <td>{{  demand.comment|default_if_none:"N/A" }}</td>
            </tr>
            <tr>
                <th scope="row">User(Create)</th>
                <td>{{  demand.user_create|default_if_none:"N/A" }}</td>
            </tr>
            <tr>
                <th scope="row">Time(Create)</th>
                <td>{{  demand.time_create|default_if_none:"N/A"|date:"Y/m/d H:i:s" }}</td>
            </tr>
            <tr>
                <th scope="row">User(Update)</th>
                <td>{{  demand.user_update|default_if_none:"N/A" }}</td>
            </tr>
            <tr>
                <th scope="row">Time(Update)</th>
                <td>{{  demand.time_update|default_if_none:"N/A"|date:"Y/m/d H:i:s" }}</td>
            </tr>
        </tbody>
    </table>
    <a href="{% url 'demand_manager:update' demand.pk %}" class="btn btn-primary"><i class="fas fa-edit"></i>Update</a>
    <a href="{% url 'demand_manager:delete' demand.pk %}" class="btn btn-secondary"><i class="fas fa-eraser"></i>Delete</a>
    <!--
    <a class="btn btn-secondary"
       data-toggle="modal" data-target="#DeleteDemandModal" data-deleteurl="{% url 'demand_manager:delete' demand.pk %}">
        <i class="fas fa-eraser"></i> Delete
    </a>
    -->
    <a href="/demand_manager/" class="btn btn-primary">Back</a>
</div>

<!--
<div class="modal fade" id="DeleteDemandModal" tabindex="-1" role="dialog"
     aria-labelledby="DeleteDemandModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
      <form action="" method="POST">
          {% csrf_token %}
          <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Deletion confirmation screen</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                  </button>
              </div>
              <div class="modal-body">
                  <p>Do you want to delete this demand?</p>
              </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                  <button type="submit" class="btn btn-primary">Delete</button>
              </div>
          </div>
      </form>
  </div>
</div>
-->

{% endblock %}

{% block extra_js %}
{% endblock %}

demand_manager/templates/demand_manager/demand_login.html
{% extends "./base.html" %}
{% block page_title %} Demand Manager Login {% endblock%}
{% block content %}
<div style="padding-top: 50px;">
    <form action="" method="POST">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body">
                    {{ form.non_field_errors }}
                    {% for field in form %}
                        {{ field }}
                        {{ field.errors }}
                        <hr>
                    {% endfor %}
                    <button type="submit" class="btn btn-lg btn-primary btn-block" >Login</button>
                    <input type="hidden" name="next" value="{{ next }}" />
                    {% csrf_token %}
                    <a class="btn btn-lg btn-outline-primary btn-block mt-2"
                       href="/accounts/user_registration/"> User Registration</a>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

demand_manager/templates/demand_manager/demand_logout.html
{% extends "./base.html" %}
{% block page_title %} Demand Manager Logout {% endblock %}
{% block content %}
    <div style="text-align: center; padding-top: 50px;">
    <h2 >See you!</h2>
    <a href="../">Login</a>
    </div>
{% endblock %}

demand_manager/templates/demand_manager/demand_top_filter.html
{% extends "./base.html"%}
{% load crispy_forms_tags %}

{% block page_title %}Demand Manager Top{% endblock %}

{% block navbar_title %}
    <a class="navbar-brand" href="{% url 'demand_manager:top' %}">Demand Manager</a>
{% endblock%}

{% block navbar_contents %}
{% include "./demand_block_navbar_contents.html" %}
{% endblock %}

{% block content %}
    <div>
        <h1><a href="{% url 'demand_manager:top' %}">Demand Manager</a></h1>
    </div>
    <!-- -->
    <div class="container">
        <h2>Demand List (Future Use)</h2>
        <div>
            <a class="btn btn-primary" href="{% url 'demand_manager:create' %}">
                <i class="far fa-calendar-plus"></i> Demand Request </a>
        </div>
        <table class="table table-bordered table-striped table-light">
            <thead>
                <tr class="table-primary">
                    <th scope="col">Product</th>
                    <th scope="col">Product ID</th>
                    <th scope="col">Technology Node</th>
                    <th scope="col">Verification</th>
                    <th scope="col">Date of Start</th>
                    <th scope="col">Date of End</th>
                    <th scope="col">Frequency [%]</th>
                    <th scope="col">Comment</th>
                </tr>
            </thead>
            <tbody>
                {% for demand in object_list_from_today %}
                    <tr>
                        <th scope="row">
                            <a href="{% url 'demand_manager:detail' demand.id %}">{{ demand.product }}</a>
                        </th>
                        <td>{{ demand.product_id }}</td>
                        <td>{{ demand.tech_node }}</td>
                        <td>{{ demand.content }}</td>
                        <td>{{ demand.start_date|date:"Y/m/d" }}</td>
                        <td>{{ demand.end_date|date:"Y/m/d"}}</td>
                        <td>{{ demand.frequency }}</td>
                        {% if demand.comment|length > 0 %}
                            <td>
                                <button type="button" class="btn btn-info" data-container="body" data-toggle="popover"
                                         data-trigger="focus" data-placement="right" data-content="{{ demand.comment }}">
                                   <i class="far fa-comment-dots"></i></button>
                            </td>
                        {% else %}
                            <td></td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <hr>
    <div class="container">
        <h2>Demand List (All)</h2>
        <div class="modal fade" id="DemandFilterModal" tabindex="-1" role="dialog"
             aria-labelledby="DemandFilterModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Search Condition</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form id="filter" method="get">
                        <div class="modal-body">
                            {{ filter.form|crispy }}
                        </div>
                    </form>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-info" form="filter">Search</button>
                    </div>
                </div>
            </div>
        </div>
        <div>
            <a class="btn btn-primary" href="{% url 'demand_manager:create' %}">
                <i class="far fa-calendar-plus"></i> Demand Request </a>
            <div class="float-right">
                <a class="btn btn-info" data-toggle="modal" data-target="#DemandFilterModal" href="#">
                    <i class="fas fa-search"></i> Search </a>
                <a class="btn btn-secondary filtered" href="/demand_manager/?page=1"> Clear Search Condition </a>
                </div>
        </div>
        <table class="table table-bordered table-striped table-light">
            <thead>
                <tr class="table-primary">
                    <th scope="col">Product</th>
                    <th scope="col">Product ID</th>
                    <th scope="col">Technology Node</th>
                    <th scope="col">Verification</th>
                    <th scope="col">Date of Start</th>
                    <th scope="col">Date of End</th>
                    <th scope="col">Frequency [%]</th>
                    <th scope="col">Comment</th>
                </tr>
            </thead>
            <tbody>
                {% for demand in object_list %}
                    <tr>
                        <th scope="row">
                            <a href="{% url 'demand_manager:detail' demand.id %}">{{ demand.product }}</a>
                        </th>
                        <td>{{ demand.product_id }}</td>
                        <td>{{ demand.tech_node }}</td>
                        <td>{{ demand.content }}</td>
                        <td>{{ demand.start_date|date:"Y/m/d" }}</td>
                        <td>{{ demand.end_date|date:"Y/m/d"}}</td>
                        <td>{{ demand.frequency }}</td>
                        {% if demand.comment|length > 0 %}
                            <td>
                                <button type="button" class="btn btn-info" data-container="body" data-toggle="popover"
                                         data-trigger="focus" data-placement="right" data-content="{{ demand.comment }}">
                                   <i class="far fa-comment-dots"></i></button>
                            </td>
                        {% else %}
                            <td></td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <nav aria-label="Page Navigation Demand">
            <ul class="pagination justify-content-center">
                <li class="page-item">
                    <a class="page-link" href="?page=1" aria-label="Top">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Top</span>
                    </a>
                </li>
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true"><</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1"><</a>
                    </li>
                {% endif %}
                {% for link_page in page_obj.paginator.page_range %}
                    {% if link_page %}
                        {% if link_page == page_obj.number %}
                            <li class="page-item active"><a class="page-link" href="#">{{ link_page }}
                                <span class="sr-only">(current)</span></a></li>
                        {% else %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ link_page }}">{{ link_page }}</a>
                            </li>
                        {% endif %}
                    {% else %}
                        <li class="page-item"><a class="page-link" href="#">...</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">></a>
                    </li>
                {% endif %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Top</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
{% endblock %}
{% block extra_js %}
    <script>
        $(function () {
            $('[data-toggle="popover"]').popover()
        })
    </script>
{% endblock %}

demand_manager/templates/demand_manager/demand_update.html
{% extends "./base.html" %}
{% load crispy_forms_tags %}
{% block page_title %} Demand Manager Demand Update {% endblock%}

{% block navbar_title %}
    <a class="navbar-brand" href="{% url 'demand_manager:top' %}">Demand Manager</a>
{% endblock%}

{% block navbar_contents %}
{% include "./demand_block_navbar_contents.html" %}
{% endblock %}


{% block content %}
<div style="padding:20px 200px 0px 200px;">
    <form action="" method="POST">
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-lg">Update</button>
        <a href="{% url 'demand_manager:top' %}" class="btn btn-primary btn-lg">Back</a>
    </form>
</div>
{% endblock %}

demand_manager/templates/demand_manager/import_released_license.html
{% extends "./base.html" %}
{% load crispy_forms_tags %}

{% block page_title %} Demand Manager Import Released License {% endblock%}

{% block navbar_title %}
    <a class="navbar-brand" href="{% url 'demand_manager:top' %}">Demand Manager</a>
{% endblock%}

{% block navbar_contents %}
{% include "./demand_block_navbar_contents.html" %}
{% endblock %}

{% block content %}
<div>
    <h1><a href="{% url 'demand_manager:top' %}">Demand Manager</a></h1>
</div>
<h2>Import Released License File</h2>
<div style="padding:20px 200px 0px 200px;">
    <form action="" method="POST" enctype="multipart/form-data">
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-lg">Add</button>
        <a href="{% url 'demand_manager:top' %}" class="btn btn-primary btn-lg">Back</a>
    </form>
</div>
{% endblock %}