accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    # ex: /
    path('', views.TopView.as_view(), name='top'),
    # ex: /login/
    path('login/', views.TopLoginView.as_view(), name='login'),
    # ex: /logout/
    path('logout/', views.TopLogoutView.as_view(), name='logout'),

    # ex: /accounts/user_registration/
    path(app_name + '/user_registration/', views.UserRegistrationView.as_view(),
         name='user_registration'),
    # ex: /accounts/user_registration/send_mail/
    path(app_name + '/user_registration/complete/send_mail/', views.UserRegistrationMailView.as_view(),
         name='user_registration_send_mail'),
    # ex: /accounts/user_registration/<token>
    path(app_name + '/user_registration/complete/<token>', views.UserRegistrationCompleteView.as_view(),
         name='user_registration_complete'),
    # ex: /accounts/profile/2/
    path(app_name + '/profile/<int:pk>/', views.UserProfileView.as_view(),
         name='profile'),
    # ex: /accounts/profile/2/update/
    path(app_name + '/profile/<int:pk>/update/', views.UserProfileUpdateView.as_view(),
         name='profile_update'),
    # ex: /accounts/profile/2/password/
    path(app_name + '/profile/<int:pk>/password_change/', views.UserPasswordChangeView.as_view(),
         name='password_change'),
    # ex: /accounts/profile/2/password/complete
    path(app_name + '/profile/<int:pk>/password/complete/', views.UserPasswordChangeCompleteView.as_view(),
         name='password_change_complete'),
    # ex: /accounts/password_reset/
    path(app_name + '/password_reset/', views.UserPasswordResetView.as_view(),
         name='password_reset'),
    # ex: /accounts/password_reset/send_mail/
    path(app_name + '/password_reset/send_mail/', views.UserPasswordResetMailView.as_view(),
         name='password_reset_send_mail'),
    # ex: /accounts/password_reset/confirm/
    path(app_name + '/password_reset/confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    # ex: /accounts/password_reset/complete/
    path(app_name + '/password_reset/complete/', views.UserPasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('accounts.urls')),
    path('demand_manager/', include('demand_manager.urls')),
    path('admin/', admin.site.urls),
]

demand_manager/urls.py
from django.urls import path
from . import views

app_name = 'demand_manager'
urlpatterns = [
    # ex: /demand_manager/
    # path('', views.DemandTopView.as_view(), name='top'),
    path('', views.DemandTopFilterView.as_view(), name='top'),

    # ex: /demand_manager/login/
    #path('login/', views.DemandLoginView.as_view(), name='login'),
    # ex: /demand_manager/logout/
    #path('logout/', views.DemandLogoutView.as_view(), name='logout'),

    # ex: /demand_manager/create/
    path('create/', views.DemandCreateView.as_view(), name='create'),
    # ex: /demand_manager//2/
    path('<int:pk>/', views.DemandDetailView.as_view(), name='detail'),
    # ex: /demand_manager/2/update/
    path('<int:pk>/update/', views.DemandUpdateView.as_view(), name='update'),
    # ex: /demand_manager/2/delete/
    path('<int:pk>/delete/', views.DemandDeleteView.as_view(), name='delete'),
    # ex: /demand_manager/analysis/
    path('analysis/', views.DemandAnalysisView.as_view(), name='analysis'),
    # ex: /demand_manager/import/
    path('import/', views.ImportReleasedLicenseView.as_view(), name='import'),
]

trialprj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('demand_manager/', include('demand_manager.urls')),
    path('admin/', admin.site.urls),
]

demand_manager/forms.py
from django import forms
from datetime import date, timedelta
from dateutil.relativedelta import relativedelta
from django.core.files.storage import default_storage
from django.core.mail import EmailMessage

from .models import Demand, Release


class DemandCreateForm(forms.ModelForm):
    """Demand Create"""

    class Meta:
        model = Demand
        fields = (
            'product', 'product_id',
            'tech_node',
            'content',
            'start_date', 'end_date',
            'frequency', 'comment'
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
        self.fields['start_date'].widget.input_type = 'date'
        self.fields['end_date'].widget.input_type = 'date'

    '''
    def clean_start_date(self):
        start_date = self.cleaned_data['start_date']
        if start_date < date.today():
            raise forms.ValidationError("The date cannot be set in the past!")
        return start_date
    '''

    def clean(self):
        start_date = self.cleaned_data['start_date']
        end_date = self.cleaned_data['end_date']
        today = date.today()
        if start_date < today:
            raise forms.ValidationError("The start date cannot be set in the past!({0} < Today: {1})"
                                        .format(start_date, today))
        elif start_date > end_date:
            raise forms.ValidationError("The end date is later than the start date(End: {0} < Start: {1})"
                                        .format(end_date, start_date))

    def send_email(self):
        product = self.cleaned_data['product']
        product_id = self.cleaned_data['product_id']
        tech_node = self.cleaned_data['tech_node']
        content = self.cleaned_data['content']
        start_date = self.cleaned_data['start_date']
        end_date = self.cleaned_data['end_date']
        frequency = self.cleaned_data['frequency']
        comment = self.cleaned_data['comment']

        subject = 'Demand Creation {0} for {1}'.format(content, product)
        message = 'From: Administrator of Demand Manager\n' + \
                  '<Registered Items>\n' + \
                  ' ' * 2 + 'Product: {}\n'.format(product) + \
                  ' ' * 2 + 'Product ID: {}\n'.format(product_id) + \
                  ' ' * 2 + 'Technology Node: {}\n'.format(tech_node) + \
                  ' ' * 2 + 'Verification Content: {}\n'.format(content) + \
                  ' ' * 2 + 'Date of Start: {}\n'.format(start_date) + \
                  ' ' * 2 + 'Date of End: {}\n'.format(end_date) + \
                  ' ' * 2 + 'Frequency[%]: {}\n'.format(frequency) + \
                  ' ' * 2 + 'Comment: {}\n'.format(comment)
        from_email = 'admin@example.com'
        to_list = ['test@example.com']
        bcc_list = ['admin@example.com']

        email = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, bcc=bcc_list)
        email.send()


class DemandUpdateForm(forms.ModelForm):
    """Demand Update"""

    class Meta:
        model = Demand
        fields = (
            'product', 'product_id',
            'tech_node',
            'content',
            'start_date', 'end_date',
            'frequency', 'comment'
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['start_date'].widget.input_type = 'date'
        self.fields['end_date'].widget.input_type = 'date'

    def clean(self):
        start_date = self.cleaned_data['start_date']
        end_date = self.cleaned_data['end_date']
        if start_date > end_date:
            raise forms.ValidationError("The end date is later than the start date")


class DemandAnalysisForm(forms.Form):
    period_start = forms.DateField(
        label="Date of Start",
        initial=date.today(),
        widget=forms.DateInput(attrs={"type":"date"}),
    )
    period_end = forms.DateField(
        label="Date of End",
        initial=date.today() + relativedelta(months=1) - timedelta(days=1),
        widget=forms.DateInput(attrs={"type":"date"}),
    )
    reference_hours = forms.IntegerField(
        label = "Reference hours per day",
        initial = 8,
    )


class ImportReleasedLicenseForm(forms.Form):
    license_type = forms.ChoiceField(
        label="License Type",
        choices=Release.lic_type_choice,
    )
    license_file = forms.FileField(
        label="License File",
        help_text="Set License File.",
    )

    def upload(self):
        upload_file = self.cleaned_data['license_file']
        license_type = self.cleaned_data['license_type']
        file_name = default_storage.save("demand_manager/license/" + upload_file.name, upload_file)
        return license_type, default_storage.url(file_name)

demand_manager/views.py
import io
import os
import logging
from django.views.generic import DetailView, FormView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django_filters.views import FilterView
from django.shortcuts import resolve_url
from django.utils import timezone
from django.urls import reverse_lazy

from datetime import datetime, date

from .models import Demand
from .forms import DemandCreateForm, DemandUpdateForm, DemandAnalysisForm, ImportReleasedLicenseForm
from .filters import DemandFilter
from demand_manager.utils.demand_summary import DemandFeature
from demand_manager.utils.import_lic import ReleaseLic

logger = logging.getLogger(__name__)


# Create your views here.
class DemandTopFilterView(LoginRequiredMixin, FilterView):
    model = Demand
    filterset_class = DemandFilter
    template_name = "demand_manager/demand_top_filter.html"

    paginate_by = 10

    '''
    def get(self, request, **kwargs):
        if request.GET:
            request.session['query'] = request.GET
        else:
            request.GET = request.GET.copy()
            if 'query' in request.session.keys():
                for key in request.session['query'].keys():
                    request.GET[key] = request.session['query'][key]
        return super().get(request, **kwargs)
    '''

    def get_queryset(self):
        return Demand.objects.all().order_by('start_date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list_from_today'] = Demand.objects.filter(end_date__gt=date.today()).order_by('start_date')
        return context


class DemandDetailView(LoginRequiredMixin, DetailView):
    model = Demand
    template_name = 'demand_manager/demand_detail.html'


class DemandCreateView(LoginRequiredMixin, CreateView):
    model = Demand
    template_name = 'demand_manager/demand_create.html'
    form_class = DemandCreateForm
    success_url = '/demand_manager'

    def form_valid(self, form):
        """

        :param form:
        :return:
        """
        demand = form.save(commit=False)
        demand.user_create = self.request.user
        demand.time_create = timezone.now()
        demand.user_update = self.request.user
        demand.time_update = timezone.now()
        demand.save()

        # Send Mail
        form.send_email()

        logger.info('Demand({0}) registered by {1}'
                    .format(form.cleaned_data['product'], demand.user_create))

        return super().form_valid(form)


class DemandUpdateView(LoginRequiredMixin, UpdateView):
    model = Demand
    template_name = 'demand_manager/demand_update.html'
    form_class = DemandUpdateForm

    def get_success_url(self):
        return resolve_url('demand_manager:detail', pk=self.kwargs['pk'])

    def form_valid(self, form):
        """

        :param form:
        :return:
        """
        demand = form.save(commit=False)
        demand.user_update = self.request.user
        demand.time_update = timezone.now()
        demand.save()

        logger.info('Demand({0}) updated by user id({1})'
                    .format(form.cleaned_data['product'], demand.user_update))

        return super().form_valid(form)


class DemandDeleteView(LoginRequiredMixin, DeleteView):
    model = Demand
    template_name = 'demand_manager/demand_delete_confirm.html'
    success_url = '/demand_manager'


class DemandAnalysisView(LoginRequiredMixin, FormView):
    form_class = DemandAnalysisForm
    template_name = 'demand_manager/demand_analysis.html'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        period_start = self.request.GET.get(key='period_start')
        period_end = self.request.GET.get(key='period_end')
        reference_hours = self.request.GET.get(key='reference_hours')
        # Calc Demand Feature
        demand_feature = DemandFeature(period_start, period_end, reference_hours)
        demand_feature.demand_summary()
        context['df_demand_feature'] = demand_feature.df_demand_feature
        context['df_summary'] = demand_feature.df_summary
        context['df_png_path'] = demand_feature.df_png_path
        if type(demand_feature.start_date) is str:
            context['period_start'] = datetime.strptime(demand_feature.start_date, '%Y-%m-%d')
        else:
            context['period_start'] = demand_feature.start_date
        if type(demand_feature.end_date) is str:
            context['period_end'] = datetime.strptime(demand_feature.end_date, '%Y-%m-%d')
        else:
            context['period_end'] = demand_feature.end_date
        context['reference_hours'] = demand_feature.ref_hours
        return context


class ImportReleasedLicenseView(LoginRequiredMixin, FormView):
    form_class = ImportReleasedLicenseForm
    template_name = 'demand_manager/import_released_license.html'
    success_url = reverse_lazy('demand_manager:top')

    def form_valid(self, form):
        lic_type, download_url = form.upload()
        ReleaseLic(lic_type, os.getcwd() + download_url).add_feature2db()
        return super().form_valid(form)

demand_manager/templates/demand_manager/old/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    {% block extra_css %}{% endblock%}

    <title>{% block page_title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'demand_manager:top' %}">Demand Manager</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'demand_manager:top' %}">
                        <i class="fas fa-home"></i> Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'demand_manager:create' %}">
                        <i class="far fa-calendar-plus"></i> Demand Request</a>
                </li>
                {% if user.is_staff %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'demand_manager:analysis' %}">
                        <i class="fas fa-chart-bar"></i> Demand Analysis</a>
                </li>
                {% endif %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownDoc" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-book"></i> Documents
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownDoc">
                        <a class="dropdown-item" href="#">Users Manual(In preparation)</a>
                        <a class="dropdown-item" href="#">Update Plan(In preparation)</a>
                        {% if user.is_staff %}
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Administrator Manual(In preparation)</a>
                        {% endif %}
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item disabled" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownLink" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-link"></i> Link
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownLink">
                        <a class="dropdown-item" href="#">Link #1</a>
                        <a class="dropdown-item" href="#">Link #2</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item disabled" href="#">Something else here</a>
                    </div>
                </li>
                <!--
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
                -->
            </ul>
            <div class="btn-group">
                <div class="btn dropdown-toggle naviDrop" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {% if user.is_authenticated %}
                       <i class="fas fa-user-circle"></i> User : {{ user.get_username }}
                    {% else %}
                        User
                    {% endif %}
                </div>
                {% if user.is_authenticated %}
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" href="{% url 'accounts:profile' user.pk %}">
                            <i class="fas fa-user-cog"></i> User Info
                        </a>
                        {% if user.is_staff %}
                            <div class="dropdown-divider"></div>
                            <h6 class="dropdown-header"> Administrator Menu </h6>
                            <a class="dropdown-item" href="{% url 'demand_manager:analysis' %}">
                                <i class="fas fa-chart-bar"></i> Demand Analysis</a>
                            <a class="dropdown-item" href="/admin/">
                                <i class="fas fa-users-cog"></i> Setup </a>
                        {% endif %}
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'demand_manager:logout' %}">
                            <i class="fas fa-sign-out-alt"></i> Logout
                        </a>
                    </div>
                {% endif %}
            </div>
            <!--
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
            -->
        </div>
    </nav>

    <div class="ui container">
        {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous">
    </script>
    {% block extra_js %}{% endblock %}
</body>
</html>

demand_manager/templates/demand_manager/old/demand_login.html
{% extends "./base.html" %}
{% load crispy_forms_tags %}
{% block page_title %} Demand Manager Login {% endblock%}
{% block content %}
<div style="padding-top: 50px;">
    <form action="" method="POST">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body">
                    {{ form|crispy }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-lg btn-primary btn-block" >Login</button>
                    <input type="hidden" name="next" value="{{ next }}" />
                    <a class="btn btn-lg btn-outline-primary btn-block mt-2"
                       href="{% url 'accounts:user_registration' %}"> User Registration</a>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

demand_manager/templates/demand_manager/old/demand_login_old.html
{% extends "./base.html" %}
{% block page_title %} Demand Manager Login {% endblock%}
{% block content %}
<div style="padding-top: 50px;">
    <form action="" method="POST">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body">
                    {{ form.non_field_errors }}
                    {% for field in form %}
                        {{ field }}
                        {{ field.errors }}
                        <hr>
                    {% endfor %}
                    <button type="submit" class="btn btn-lg btn-primary btn-block" >Login</button>
                    <input type="hidden" name="next" value="{{ next }}" />
                    {% csrf_token %}
                    <a class="btn btn-lg btn-outline-primary btn-block mt-2"
                       href="/accounts/user_registration/"> User Registration</a>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

demand_manager/templates/demand_manager/old/demand_logout.html
{% extends "./base.html" %}
{% block page_title %} Demand Manager Logout {% endblock %}
{% block content %}
    <div style="text-align: center; padding-top: 50px;">
    <h2 >See you!</h2>
    <a href="{% url 'demand_manager:login' %}">Login</a>
    </div>
{% endblock %}

demand_manager/templates/demand_manager/old/demand_top.html
{% extends "./base.html"%}

{% block page_title %}Demand Manager Top{% endblock %}

{% block content %}
    <div>
        <h1><a href="/demand_manager">Demand Manager</a></h1>
    </div>

    <div>
        <h2>Demand List</h2>
        <table class="table table-bordered table-striped table-light">
            <thead>
                <tr class="table-primary">
                    <th scope="col">Product</th>
                    <th scope="col">Technology Node</th>
                    <th scope="col">Verification</th>
                </tr>
            </thead>
            <tbody>
                {% for demand in object_list %}
                    <tr>
                        <th scope="row">
                            <a href="{% url 'demand_manager:detail' demand.id %}">{{ demand.product }}</a>
                        </th>
                        <td>{{ demand.tech_node }}</td>
                        <td>{{ demand.content }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <a class="btn btn-primary" href="/demand_manager/create/"><i class="far fa-calendar-plus"></i> Demand Request </a>
{% endblock %}